### ISSUE TITLE
NoReverseMatch at /facebook/connect/

### ISSUE THREAD

**Issue by browsewire** [tschellenbach/Django-facebook#138]
Hello There,

I am using Django_Facebook  application in one of my django application. After making facebook application and updating my setting.py, urls.py.

My Settings are: 
AUTH_PROFILE_MODULE = 'django_facebook.FacebookProfile'
FACEBOOK_REGISTRATION_BACKEND = 'django_facebook.registration_backends.UserenaBackend'

As I am trying to access my application hare is the url: http://onelinersjoe.com.47.69-195-199.groveurl.com/facebook/connect/

I am getting an error: 
+++
NoReverseMatch at /facebook/connect/

Reverse for 'django.contrib.auth.views.logout' with arguments '()' and keyword arguments '{}' not found.

Request Method:     GET
Request URL:    http://onelinersjoe.com.47.69-195-199.groveurl.com/facebook/connect/
Django Version:     1.4
Exception Type:     NoReverseMatch
Exception Value:    

Reverse for 'django.contrib.auth.views.logout' with arguments '()' and keyword arguments '{}' not found.

Exception Location:     /usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py in render, line 424
Python Executable:  /usr/bin/python
Python Version:     2.7.1
Python Path:    

['/var/www/vhosts/onelinersjoe.com/httpdocs/oneliners',
 '/usr/local/lib/python2.7/dist-packages/django',
 '/usr/local/lib/python2.7/dist-packages/pip-1.1-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/virtualenv-1.7.1.2-py2.7.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/local/lib/python2.7/dist-packages/PIL',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/pymodules/python2.7']

Server time:    Sat, 2 Jun 2012 02:22:13 -0500

I edited my connect.html template and got the line where is it coming from here is the line: 
+++
{% if request.user.is_authenticated %}
        

I f I remove this line everything is working fine, What is wrong in its syntax or how could I change the above line so that it works fine, kindly help with proper detail instruction as I am new to django and struggling with it from last few days.

---Browsewire

**Comment by asgaines** [comment]
The problem I'm encountering seems to be due to not linking the line
```python
(r'^accounts/', include('django_facebook.auth_urls')), #Don't add this line if you use django registration or userena for registration and auth.
```
in `urls.py`. Yet, as stated in the comment, I don't want to be using this since I'm using the Django authentication/registration system. When routing from `/facebook/example`, django_facebook uses a page which has a url tag to a reversed url in the `auth_urls` module.
