### ISSUE TITLE
Problem AUTH_USER_MODEL set to 'member.FacebookUser'

### ISSUE THREAD

**Issue by filipeximenes** [tschellenbach/Django-facebook#312]
`AUTH_USER_MODEL = 'member.FacebookUser'`
is returning the error:
`django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'member.FacebookUser' that has not been installed`

I'm working with the following configuration:

```
Django==1.5.1
django-facebook==5.1.1
```

**Comment by SaurabhGujjar** [comment]
Just register your models in admin.py.
like-- admin.site.register(FacebookUser)
