### ISSUE TITLE
Exceptions Handling Existing Email on Registration

### ISSUE THREAD

**Issue by kacecode** [tschellenbach/Django-facebook#331]
So, prior to upgrading to 5.10, I seem to recall Django-Facebook auto-magically checking to see if a user's email account already existed and if it did, the Facebook account would be merged on top of it.

Now we're seeing users being dropped to a form with validation errors for the email already having been taken.

Has this functionality been changed?

**Comment by dsnstudio** [comment]
Hi, i changed the line 232:
`if data['email'] ...`
for 
`if data.get('email','empty') == 'empty':`
this way it checks the data array for key 'email' without raising errors and if not find it, give a default value for later checking/manipulation.

this was updated in connect.py code some time ago.
