### ISSUE TITLE
What should be the Site URL in facebook app settings to work from localhost?

### ISSUE THREAD

**Issue by xpanta** [tschellenbach/Django-facebook#376]
I am trying to work with the example page (/facebook/example/) from localhost and I always get "Given URL is not permitted by the application configuration.: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains."

In my Site URL (Facebook app settings) I have this: http://127.0.0.1:8000/facebook/example/

Is it possible to work from locahost? How?

**Comment by rrohitramsen** [comment]
I am not able to redirect back to localhost. My app is at facebook canvas page "https://apps.facebook.com/springyellow/?code=AQCvDp_FbBCfeI2SiWEBPGiQpY" . I tried all .

**Comment by Tig10** [comment]
@ gaganphp, It appears the Website URL field is a 'required' field. It cannot be empty. I am still having this issue persisting even though I have set my localhost url on Valid OAuth redirect URIs.

**Comment by rmercer33** [comment]
Hey xpanta, coming to you from 2016, your solution worked for me!!! Many  thanks.

**Comment by dpasie2** [comment]
Thank you @xpanta ! Cured my headache!

**Comment by shtaabhishek** [comment]
thank you @xpanta and @gaganphp for the soln

**Comment by giangnguyennet** [comment]
It doesn't seem to have `Valid OAuth redirect URIs` in the Settings > Advanced tab anymore as of May 2016. Or am I missing something? Thanks!

![Facebook app setting](https://www.evernote.com/l/AtGEsFF7Sr5M1640nZ_JIYyKydGP9b72rPQB/image.png)

**Comment by mbaggio** [comment]
They changed the layout. 
OAuth section is now placed here:

<img width="1208" alt="oauth redirect config 2" src="https://cloud.githubusercontent.com/assets/11964506/15117414/d11ea3d2-15dd-11e6-951c-d2fc15865759.png">

**Comment by chis** [comment]
Add product -> Facebook Login.
Goto product settings.
Enter 'http://localhost:5000' [with your correct port] under 'Valid OAuth redirect URIs' 
This worked for me.

**Comment by daho16** [comment]
thank's man

**Comment by parthiban26** [comment]
i am also having same problem, whenever i tried to login via facebook i will get below error 
error:
given url is not allowed by the application configuration one or more of the given url is not allowed by bthe app settings to use this url you must add a valid native platform in your app settings

so, please give any suggestions.

**Comment by parthiban26** [comment]
i need to finish this task ASAP, So please give solution..

**Comment by parthiban26** [comment]
i am using ionic app, with development stage..

**Comment by jsvaughan** [comment]
parthiban26 - does this help?: http://stackoverflow.com/questions/31883079/ios-facebook-login-given-url-is-not-allowed-by-the-application-configuration

**Comment by zumzar96** [comment]
I'm trying to allow users to login with facebook via django allauth to my website but I am getting the following error:
URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.
I configured my Facebook app like this:
1.Made it Public
2.Website
site URL: http://localhost:8000/ (since I'm running locally)
3. App Domains:Empty
4.Client OAuth Login -ON
   Web OAuth Login -ON
5.Valid OAuth redirect URIs: http://localhost:8000/

**Comment by panamantis** [comment]
Add a custom domain url in your hosts file (if on windows) to mast the localhost or 127.0.0.1

**Comment by purnimakumari748** [comment]
I applied the above solution but it still not working for me .. it showing error --

"URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs"
**my fb configrations :-**
1-Valid OAuth redirect URIs:  http://localhost:8000/demo/index/
2- App Domains:Empty
3-Client OAuth Login -O
4-Web OAuth Login -ON
5-Website
site URL: empty
Please suggest solution

**Comment by Tig10** [comment]
Try this:
App Domians: http://localhost/
Site URL: http://localhost/
Then in the Facebook Login Product settings;
Valid OAuth redirect URIs:
http://localhost/  http://localhost/demo http://localhost/demo/index

This should work if not then add your port to every http://localhost:80 part of these entries. Let me know how it goes.

**Comment by mkgdev** [comment]
I am getting localhost refused to connect in chrome while using passport-facebook . Can anyone help me!

**Comment by purnimakumari748** [comment]
still showing same error and in domain i am puting http://localhost, its
automatically taking localhost only .

**Comment by faiaz000** [comment]
Still not working

**Comment by alboteanud** [comment]
not working. I think, generating your own SSL certificate for testing is a better solution https://stackoverflow.com/questions/8169999/how-can-i-create-a-self-signed-cert-for-localhost

**Comment by himanshutyagi623** [comment]
Hello
my website is www.xyz.com and what will be my valid oauth redirect url
i entered www.xyz.com/my-account/facebook/int_callback but its working all the process but not login to my fb account
Please help soon

**Comment by vaibhav011286** [comment]
Hello,
I setup wamp with virtual host like https://abc, so how can I make this url work for fb login? plz help

**Comment by saurabhp75** [comment]
The solution is not working for me.  Is there any change in facebook implementation. I am using flask dance and my oauth url is https://localhost:5000/login/facebook/authorize

**Comment by kenmorechalfant** [comment]
Facebook no longer allows you to add URIs that are not HTTPS, so I can't add localhost.

When I try to log into my app during development I now get an error "This IP can't make requests for that application."

Any current solutions?

**Comment by hugoscavino** [comment]
You can create a local cert using https for localhost.

**Comment by xxRockOnxx** [comment]
There's something called "Test App" now. It's hidden so it isn't obvious that you have to create one.
Found the answer here: https://stackoverflow.com/a/57607570/10975709
