### ISSUE TITLE
integration with custom user model using  USERNAME_FIELD = 'email' 

### ISSUE THREAD

**Issue by cis-yogesh** [tschellenbach/Django-facebook#385]
I intregating  django-facebook with custom user model, i am getting this error 
FieldError: Cannot resolve keyword 'username' into field. Choices are: message, opengraphshare, password, profile_pic, region  twitter, updated, user_permissions, verification_code.
My settings are:
# modle.py is

class MyUser(AbstractBaseUser):
    email = models.EmailField(max_length=254, unique=True, db_index=True)
    twitter_handle = models.CharField(max_length=255)

```
is_active = models.BooleanField(default=True)
is_admin = models.BooleanField(default=False)

objects = MyUserManager()

USERNAME_FIELD = 'email'
REQUIRED_FIELDS = ['twitter_handle']
```

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
# In setting.py

AUTH_USER_MODEL = 'myapp.MyUser'

AUTHENTICATION_BACKENDS = (
    'django_facebook.auth_backends.FacebookBackend',
    'django.contrib.auth.backends.ModelBackend',
)

AUTH_PROFILE_MODULE = "myapp.MyUser"
Please let help me what i am doing wrong here.
Thanks
Yogesh

**Comment by xpostudio4** [comment]
HI @tschellenbach ,

Can you give me any suggestion what would you do to solve this case?, I can do it and later see how to add it to the code of Django-facebook.
