### ISSUE TITLE
Release a new version to pypi

### ISSUE THREAD

**Issue by troygrosfield** [tschellenbach/Django-facebook#538]
I'm seeing errors that have already been fixed in master (OpenFacebook permissions() method).  Can we get a new release out to pypi?  Last release was 2014-10-16.

**Comment by tschellenbach** [comment]
sure, anything else you want to add?
I can do a release later today.

On Tue, May 26, 2015 at 2:55 PM, Troy Grosfield <notifications@github.com>
wrote:

> I'm seeing errors that have already been fixed in master (OpenFacebook
> permissions() method). Can we get a new release out to pypi? Last release
> was 2014-10-16.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tschellenbach/Django-facebook/issues/538>.
>



-- 
*Thierry Schellenbach* | Founder/CEO GetStream.io <https://getstream.io/> |
Techstars NYC 2015
 LinkedIn <http://www.linkedin.com/in/thierryschellenbach> | *E.*
thierry@getstream.io | *Twitter* @tschellenbach
<http://www.twitter.com/tschellenbach> | *Blog *mellowmorning.com | Github
<https://github.com/tschellenbach>

**Comment by troygrosfield** [comment]
Most of the issues I'm seeing have already been fixed in master.  The one that I would LOVE to get resolved is getting the test suite green again: 

- https://github.com/tschellenbach/Django-facebook/issues/537

That way we know the releases are at least passing tests runs.  There only seems to be a few errors that are causing all the problems (see #537 for descriptions).

As always, thanks for the prompt response @tschellenbach!

**Comment by tschellenbach** [comment]
Thanks so much for helping out. I'd love to see this library in good shape.
It's just that my current projects dont interact with Facebook, so it's
hard to find time...

Best,
Thierry

**Comment by tschellenbach** [comment]
I've just pushed master to 6.0.3
https://pypi.python.org/pypi/django-facebook/6.0.3

Let me know when you want to push another update.

**Comment by troygrosfield** [comment]
Awesome!  My tests all pass locally after the update.  So that's a start.  I'll try and look into the test suite errors later.

Thanks again!
