### ISSUE TITLE
Drop support for django 1.6 and 1.7, test against django 1.9 and python 3.5

### ISSUE THREAD

**Issue by troygrosfield** [tschellenbach/Django-facebook#559]
Django [no longer supports](https://www.djangoproject.com/download/#supported-versions) version 1.6 or 1.7, so I would recommend django-facebook dropping support for those versions as well.  

Also, django 1.9 and python 3.5 were release so we need to get those added to ``.travis.yml`` so we're at least testing against them.

**Comment by troygrosfield** [comment]
@tschellenbach, I know you're more hands off on this now, but what are your thoughts about dropping support for django 1.6 and 1.7?

**Comment by tschellenbach** [comment]
Hi Troy, Yeay I wish I could find some time for Django-Facebook. It's pretty busy over here :)

I totally agree with dropping 1.6 and 1.7 and adding support for 1.9

**Comment by troygrosfield** [comment]
Cool.  I'll look into in in a bit.

**Comment by lukaskris** [comment]
Could you help me config install django facebook using django 1.10
