### ISSUE TITLE
Upgrade to django 1.11

### ISSUE THREAD

**Issue by shivashishrs** [tschellenbach/Django-facebook#597]
Since we are using django version 1.11 so their are many error developer should solve. I changed code to bypass context processor check so I stuck on url pattern error because django have removed django.conf.urls.patterns for 1.10 and there are too many things to be upgraded.

**Comment by Allan-Nava** [comment]
Any news?

**Comment by tschellenbach** [comment]
Pull request would be appreciated

**Comment by Allan-Nava** [comment]
Is still alive the project?
